services:
  martin:
    image: maplibre/martin:latest
    restart: unless-stopped
    ports:
      - "5433:3000"
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db/${DATABASE_NAME}
    depends_on:
      - db

  db:
    build: 
      context: ./db
      args:
        - STORAGE_URL=${STORAGE_URL}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db-volume:/var/lib/postgresql/data
