services:
  db:
    build:
      context: ./db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "8010:5432"
    networks:
      - data
    volumes:
      - ./db-volume:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4GB
networks:
  data:
