CREATE TABLE "cbbr_agency_need" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cbbr_agency_need_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"agency_initials" text NOT NULL,
	"need_id" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cbbr_agency_need_group" (
	"agency_initials" text NOT NULL,
	"need_group_id" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cbbr_agency_need_request" (
	"agency_need_id" smallint NOT NULL,
	"request_id" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cbbr_need" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cbbr_need_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"description" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cbbr_need_group" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cbbr_need_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	"policy_area_id" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cbbr_policy_area" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cbbr_policy_area_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"description" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cbbr_request" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cbbr_request_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	"type" text NOT NULL,
	CONSTRAINT "cbbr_request_type_options" CHECK ("cbbr_request"."type" IN ('Capital', 'Expense'))
);
--> statement-breakpoint
ALTER TABLE "cbbr_agency_need" ADD CONSTRAINT "cbbr_agency_need_agency_initials_agency_initials_fk" FOREIGN KEY ("agency_initials") REFERENCES "public"."agency"("initials") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cbbr_agency_need" ADD CONSTRAINT "cbbr_agency_need_need_id_cbbr_need_id_fk" FOREIGN KEY ("need_id") REFERENCES "public"."cbbr_need"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cbbr_agency_need_group" ADD CONSTRAINT "cbbr_agency_need_group_agency_initials_agency_initials_fk" FOREIGN KEY ("agency_initials") REFERENCES "public"."agency"("initials") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cbbr_agency_need_group" ADD CONSTRAINT "cbbr_agency_need_group_need_group_id_cbbr_need_group_id_fk" FOREIGN KEY ("need_group_id") REFERENCES "public"."cbbr_need_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cbbr_agency_need_request" ADD CONSTRAINT "cbbr_agency_need_request_agency_need_id_cbbr_agency_need_id_fk" FOREIGN KEY ("agency_need_id") REFERENCES "public"."cbbr_agency_need"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cbbr_agency_need_request" ADD CONSTRAINT "cbbr_agency_need_request_request_id_cbbr_request_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."cbbr_request"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cbbr_need_group" ADD CONSTRAINT "cbbr_need_group_policy_area_id_cbbr_policy_area_id_fk" FOREIGN KEY ("policy_area_id") REFERENCES "public"."cbbr_policy_area"("id") ON DELETE no action ON UPDATE no action;