CREATE TABLE "cbbr_agency_category_response" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cbbr_agency_category_response_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"description" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "community_board_budget_request" (
	"id" text PRIMARY KEY NOT NULL,
	"internal_id" text NOT NULL,
	"borough_id" char(1) NOT NULL,
	"community_district_id" char(2) NOT NULL,
	"agency" text NOT NULL,
	"managing_code" char(3) NOT NULL,
	"agency_category_response_id" smallint NOT NULL,
	"agency_response" text,
	"request_type" text NOT NULL,
	"policy_area_id" smallint NOT NULL,
	"need_group_id" smallint NOT NULL,
	"priority" smallint NOT NULL,
	"need_id" smallint NOT NULL,
	"request_id" smallint,
	"explanation" text,
	"is_location_specific" boolean NOT NULL,
	"li_ft_m_pnt" geometry(multiPoint,2263),
	"li_ft_m_poly" geometry(multiPolygon,2263),
	"mercator_label" geometry(point,3857),
	"mercator_fill_m_pnt" geometry(multiPoint,3857),
	"mercator_fill_m_poly" geometry(multiPolygon,3857),
	CONSTRAINT "community_board_budget_request_request_type_options" CHECK ("community_board_budget_request"."request_type" IN (
        'Capital',
        'Expense'
      ))
);
--> statement-breakpoint
ALTER TABLE "community_board_budget_request" ADD CONSTRAINT "community_board_budget_request_agency_agency_initials_fk" FOREIGN KEY ("agency") REFERENCES "public"."agency"("initials") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "community_board_budget_request" ADD CONSTRAINT "community_board_budget_request_managing_code_managing_code_id_fk" FOREIGN KEY ("managing_code") REFERENCES "public"."managing_code"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "community_board_budget_request" ADD CONSTRAINT "community_board_budget_request_agency_category_response_id_cbbr_agency_category_response_id_fk" FOREIGN KEY ("agency_category_response_id") REFERENCES "public"."cbbr_agency_category_response"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "community_board_budget_request" ADD CONSTRAINT "community_board_budget_request_policy_area_id_cbbr_policy_area_id_fk" FOREIGN KEY ("policy_area_id") REFERENCES "public"."cbbr_policy_area"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "community_board_budget_request" ADD CONSTRAINT "community_board_budget_request_need_group_id_cbbr_need_group_id_fk" FOREIGN KEY ("need_group_id") REFERENCES "public"."cbbr_need_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "community_board_budget_request" ADD CONSTRAINT "community_board_budget_request_need_id_cbbr_need_id_fk" FOREIGN KEY ("need_id") REFERENCES "public"."cbbr_need"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "community_board_budget_request" ADD CONSTRAINT "community_board_budget_request_request_id_cbbr_request_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."cbbr_request"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "community_board_budget_request" ADD CONSTRAINT "community_board_budget_request_borough_id_community_district_id_community_district_borough_id_id_fk" FOREIGN KEY ("borough_id","community_district_id") REFERENCES "public"."community_district"("borough_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "community_board_budget_request_li_ft_m_pnt_index" ON "community_board_budget_request" USING GIST ("li_ft_m_pnt");--> statement-breakpoint
CREATE INDEX "community_board_budget_request_li_ft_m_poly_index" ON "community_board_budget_request" USING GIST ("li_ft_m_poly");--> statement-breakpoint
CREATE INDEX "community_board_budget_request_mercator_label_index" ON "community_board_budget_request" USING GIST ("mercator_label");--> statement-breakpoint
CREATE INDEX "community_board_budget_request_mercator_fill_m_poly_index" ON "community_board_budget_request" USING GIST ("mercator_fill_m_poly");--> statement-breakpoint
CREATE INDEX "community_board_budget_request_mercator_fill_m_pnt_index" ON "community_board_budget_request" USING GIST ("mercator_fill_m_pnt");