CREATE TABLE "facility_domain" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "facility_domain_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"name" text,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "facility_group" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "facility_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"name" text,
	"description" text,
	"facility_domain_id" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "facility_subgroup" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "facility_subgroup_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"name" text,
	"description" text,
	"facility_group_id" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "facility_type" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "facility_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"name" text,
	"facility_subgroup_id" smallint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "facility_group" ADD CONSTRAINT "facility_group_facility_domain_id_facility_domain_id_fk" FOREIGN KEY ("facility_domain_id") REFERENCES "public"."facility_domain"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facility_subgroup" ADD CONSTRAINT "facility_subgroup_facility_group_id_facility_group_id_fk" FOREIGN KEY ("facility_group_id") REFERENCES "public"."facility_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facility_type" ADD CONSTRAINT "facility_type_facility_subgroup_id_facility_subgroup_id_fk" FOREIGN KEY ("facility_subgroup_id") REFERENCES "public"."facility_subgroup"("id") ON DELETE no action ON UPDATE no action;